export { ClassicTemplate } from "./classic-template"
export { ProfessionalTemplate } from "./professional-template"
export { ModernTemplate } from "./modern-template"
export { BusinessTemplate } from "./business-template"
export { ProjectTemplate } from "./project-template"
export { CreativeTemplate } from "./creative-template"
export { ClientTemplate, clientTemplatePages } from "./client-template"
export { StartupTemplate } from "./startup-template"
export { MarketingTemplate } from "./marketing-template"
export { TechnicalTemplate } from "./technical-template"
export { ConsultingTemplate } from "./consulting-template"
export { ExecutiveTemplate } from "./executive-template"
export { MinimalTemplate } from "./minimal-template"
export { AgencyTemplate } from "./agency-template"
export { EnterpriseTemplate } from "./enterprise-template"
export { FinancialTemplate } from "./financial-template"
export { PartnershipTemplate } from "./partnership-template"
export { PagedTemplate } from "./paged-template"
export type { TemplateProps } from "./types"
